version: "3.8"
services:
  web-fe:
    image: zeinebbenali/magazin-application:1.10
    command: bash -c "java -jar app.jar"
    container_name: magazin-application
    deploy:
      replicas: 1
    ports:
      - target: 8090
        published: 5001
    networks:
      - elk
networks:
  elk:
    driver: bridge

volumes:
  esdata01:
    driver: local