version: "3.8"
services:
  web-fe:
    image: zeinebbenali/magazin-application:1.5
    command: bash -c "java -jar app.jar"
    deploy:
      replicas: 1
    ports:
      - target: 8090
        published: 5001
    networks:
      - counter-net
networks:
  counter-net:

volumes:
  counter-vol: