version: '3.2'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    container_name: elasticsearch
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks
      # see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:7.3.1
    container_name: logstash
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch


  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.1
    container_name: kibana
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch


  apm-server:
    container_name: apm-server
    image: docker.elastic.co/apm/apm-server:7.3.1
    ports:
      - "8200:8200"
    networks:
      - elk
    depends_on:
      - elasticsearch
    volumes:
      - ./apm-server/config/apm-server.yml:/usr/share/apm-server/config/apm-server.yml:ro,z
    command: [
        "apm-server",
        "-e",
        "-E", "output.elasticsearch.username=elastic",
        "-E", "output.elasticsearch.password=changeme",
    ]

  filebeat:
    networks:
      - elk
    depends_on:
      - elasticsearch
    image: docker.elastic.co/beats/filebeat:7.3.1
    container_name: filebeat
    volumes:
      - type: bind
        source: ./filebeat/config/filebeat.yml
        target: /usr/share/filebeat/config/filebeat.yml
        read_only: true
      - type: bind
        source: /var/lib/docker/containers
        target: /usr/share/filebeat/dockerlogs
        read_only: true
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock

volumes:
  elasticsearch:

networks:
  elk:
    driver: bridge